# Build site settings
remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
gem "github-pages", group: :jekyll_plugins
title: Snake Debate Chatbot
description: This is the GitHub for Snake Debate Chatbot. A chatbot which debates people about common snake myths and misconceptions
show_downloads: true
