# Build site settings
remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
gem "github-pages", group: :jekyll_plugins
title: CS 4395.001 Human Language Technologies
description: This is a github to store my Human Language Technology projects from my CS 4395.001 class.
show_downloads: true
